[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
fuels = { version = "0.25", features = ["fuel-core-lib"] }
anyhow = "1.0.66"
forc-pkg = "0.30.1"
forc-tracing = "0.30.1"
fuel-core-interfaces = "0.10.1"
gag = "1.0.0"
regex = "1.7.0"
tokio = { version = "1.12", features = ["rt", "macros"] }
tracing = "0.1.37"
rand = "0.8.5"
prelude = "0.2.1"
